<?php
/**
 * Created by PhpStorm.
 * User: dario
 * Date: 24/01/18
 * Time: 13.03
 */
?>
<br>
<footer class="footer">
    <div class="container">
        <div class="content has-text-centered">
            <p>
                Creato da <strong>Dario Pagani</strong> ed <strong>Enrico Guerra</strong> nell'anno scolastico 2017-2018
            </p>
            <a class="button" href="https://github.com/DarioPagani/db_tirocinio" target="_blank">
                <span class="icon">
                    <i class="fa fa-github" aria-hidden="true"></i>
                </span>
                <span>
                    GitHub
                </span>
            </a>
            <a href="https://bulma.io" target="_blank">
                <img src="<?= BASE_DIR ?>asset/made-with-bulma.png" alt="Made with Bulma" width="192" height="36">
            </a>
            <p class="help">
                <?php
                $quotes = json_decode(file_get_contents(dirname(__FILE__) . "/quotes.json"));

                echo $quotes[array_rand($quotes, 1)];
                ?>
            </p>
        </div>
    </div>
</footer>
