<?php
/**
 * Created by PhpStorm.
 * User: dario
 * Date: 18/01/18
 * Time: 15.18
 */
?>
<!-- config -->
<!--<base href="<?= BASE_DIR ?>" >-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>
    <?php
        echo SITE_NAME;

        if(isset($page))
            echo " - " . filter_var($page, FILTER_SANITIZE_FULL_SPECIAL_CHARS);
    ?>
</title>

<!-- Cosnati JS ed altro -->
<script>
	const BASE = "<?= BASE_DIR ?>";

	/**
     * È una stringa?
     * @author https://stackoverflow.com/a/17772086
	 * @param x
	 * @return {boolean}
	 */
	function isString(x)
    {
		return Object.prototype.toString.call(x) === "[object String]"
	}
</script>

<!-- JavaScript -->
<script src="<?= BASE_DIR ?>js/lib/jquery-3.3.1.min.js"></script>
<script src="<?= BASE_DIR ?>js/lib/jquery.urlParam.js"></script>
<script src="<?= BASE_DIR ?>js/global.js"></script>

<!-- CSS -->
<link rel="stylesheet" href="<?= BASE_DIR ?>css/bulma.min.css">
<link rel="stylesheet" href="<?= BASE_DIR ?>css/font-awesome-4.7.0/css/font-awesome.min.css">
<style>
    .overflow
    {
        overflow-x: auto;
        overflow-y: auto;
    }
</style>