<?php
/**
 * Created by PhpStorm.
 * User: dario
 * Date: 18/01/18
 * Time: 15.18
 */
?>
<!-- config -->
<!--<base href="<?= BASE_DIR ?>" >-->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>
    <?php
        echo SITE_NAME;

        if(isset($page))
            echo " - {$page}";
    ?>
</title>

<!-- CSS -->
<link rel="stylesheet" href="<?= BASE_DIR ?>css/bulma.min.css">
<link rel="stylesheet" href="<?= BASE_DIR ?>css/font-awesome-4.7.0/css/font-awesome.min.css">

<!-- JavaScript -->
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

<!-- Cosnati JS -->
<script>
	const BASE = "<?= BASE_DIR ?>";
</script>