<?php
/**
 * Created by PhpStorm.
 * User: dario
 * Date: 13/04/18
 * Time: 18.01
 */

?>

<!--- PopOut: Seleziona Aziende -->
<div class="modal" id="azienda_modal">
    <div class="modal-background"></div>
    <div class="modal-card">
        <header class="modal-card-head">
            <p class="modal-card-title">Selezione azienda</p>
        </header>
        <section class="modal-card-body" style="height: 100%; max-height: 100%">
            <div class="level">
                <!-- Left side -->
                <div class="level-left">
                    <form id="azienda_cerca">
                        <div class="field has-addons">
                            <p class="control">
                                <input class="input" name="query" type="text" placeholder="Filtra">
                            </p>
                            <p class="control">
                                <button type="submit" class="button">
                                    Cerca
                                </button>
                            </p>
                        </div>
                    </form>
                </div>

                <div class="level-right">
                    <div class="field has-addons">
                        <p class="control">
                            <button class="button" disabled id="azienda_back">Indietro</button>
                        </p>
                        <p class="control">
                            <button class="button" disabled id="azienda_forward">Avanti</button>
                        </p>
                    </div>
                </div>
            </div>
            <div class="is-fullwidth" style="overflow-y: auto">
                <table class="table is-fullwidth is-narrow is-hoverable">
                    <thead>
                    <tr>
                        <th>Nominativo</th>
                        <th>IVA</th>
                        <th>C. Fiscale</th>
                        <th style="width: 10%"></th>
                    </tr>
                    </thead>
                    <tbody id="aziende_tbody">

                    </tbody>
                </table>
            </div>
        </section>
        <footer class="modal-card-foot">
            <button class="button is-success" id="seleziona_azienda_aggiungi">Seleziona</button>
            <button class="button" id="seleziona_azienda_scarta">Scarta</button>
        </footer>
    </div>
</div>
<script src="<?= BASE_DIR ?>pages/docente/modals/js/Azienda.js"></script>